:concurrency: 5
:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    nightly_maintenance:
      cron: "0 4 * * *"  # 4 AM UTC = midnight EDT
      class: ScheduleMaintenanceJob
      queue: default
      description: "Schedule maintenance tasks for all empires"
